// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate_usb_vendor_list.py
// Source: https://www.usb.org/sites/default/files/vendor_ids121720_3.pdf
// Generated: 2026-01-04 18:35:35

#pragma once

#include <string>
#include <Windows.h>

namespace KDM
{

/// <summary>
/// Structure representing a USB vendor ID and name pair.
/// </summary>
struct UsbVendorInfo {
    USHORT vendorId;
    const wchar_t* vendorName;
};

/// <summary>
/// Retrieves the vendor name for a given USB vendor ID.
/// </summary>
/// <param name="vendorId">The USB vendor ID to look up</param>
/// <returns>The vendor name, or "Unknown" if not found</returns>
[[nodiscard]] const std::wstring GetVendorStringById(USHORT vendorId);

/// <summary>
/// Returns the total number of known USB vendors.
/// </summary>
[[nodiscard]] size_t GetVendorCount() noexcept;

}  // namespace KDM
